# Generated by Django 4.2.3 on 2023-09-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('ScName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ScPrincipal', models.CharField(max_length=100)),
                ('ScLoc', models.CharField(max_length=100)),
                ('ScId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('Sname', models.CharField(max_length=100)),
                ('ClassName', models.CharField(max_length=100)),
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('ScName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
